server:
  port: 9200
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: localhost
        port: 8500
        discovery:
          serviceName: ${spring.application.name}