server:
  port: 9001
  servlet:
    context-path: /uaa
spring:
  application:
    name: oauth-server
  cloud:
    consul:
      host: 127.0.0.1
      discovery:
        service-name: ${spring.application.name}